name: Build and Push Docker Image to Aliyun ACR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录到阿里云 ACR
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      # 构建并推送 Docker 镜像（latest）
      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.ALIYUN_REGISTRY }}/reuben_home/blog-news-apis
          docker build -t $IMAGE:latest .
          docker push $IMAGE:latest
