name: Build and Push Docker Image to Aliyun ACR

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录到阿里云 ACR
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          IMAGE=${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ secrets.ALIYUN_REPO }}
          TAG=${GITHUB_SHA::7}
          echo "IMAGE=$IMAGE:$TAG"
          docker build -t $IMAGE:$TAG .

      # 推送到阿里云
      - name: Push Docker Image
        run: |
          IMAGE=${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ secrets.ALIYUN_REPO }}
          TAG=${GITHUB_SHA::7}
          docker push $IMAGE:$TAG

      # （可选）打 latest 标签
      - name: Push latest tag
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          IMAGE=${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ secrets.ALIYUN_REPO }}
          docker tag $IMAGE:${GITHUB_SHA::7} $IMAGE:latest
          docker push $IMAGE:latest
